// Date: 2/05/2013 1:54:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.smitecraft.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelZeusMob extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer shoulderright;
    ModelRenderer shoulderleft;
    ModelRenderer spikeleft;
    ModelRenderer shodleft;
    ModelRenderer shodright;
    ModelRenderer spikeright;
  
  public ModelZeusMob()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, -4F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 13);
      body.addBox(-4F, 0F, -2F, 8, 15, 4);
      body.setRotationPoint(0F, -4F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 13);
      rightarm.addBox(-3F, -6F, -2F, 4, 15, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 13);
      leftarm.addBox(-1F, -2F, -2F, 4, 15, 4);
      leftarm.setRotationPoint(5F, -2F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 13, 4);
      rightleg.setRotationPoint(-2F, 11F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 13, 4);
      leftleg.setRotationPoint(2F, 11F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      shoulderright = new ModelRenderer(this, 35, 0);
      shoulderright.addBox(0F, -1F, 0F, 1, 3, 2);
      shoulderright.setRotationPoint(-8F, -6F, 0F);
      shoulderright.setTextureSize(64, 32);
      shoulderright.mirror = true;
      setRotation(shoulderright, 0F, 0F, 0F);
      shoulderleft = new ModelRenderer(this, 36, 8);
      shoulderleft.addBox(0F, -1F, 0F, 1, 3, 2);
      shoulderleft.setRotationPoint(7F, -6F, 0F);
      shoulderleft.setTextureSize(64, 32);
      shoulderleft.mirror = true;
      setRotation(shoulderleft, 0F, 0F, 0F);
      spikeleft = new ModelRenderer(this, 57, 1);
      spikeleft.addBox(0F, 0F, 0F, 1, 1, 2);
      spikeleft.setRotationPoint(7F, -9F, 2F);
      spikeleft.setTextureSize(64, 32);
      spikeleft.mirror = true;
      setRotation(spikeleft, 0F, 0F, 0F);
      shodleft = new ModelRenderer(this, 57, 5);
      shodleft.addBox(0F, -1F, 0F, 1, 2, 2);
      shodleft.setRotationPoint(7F, -7F, 1F);
      shodleft.setTextureSize(64, 32);
      shodleft.mirror = true;
      setRotation(shodleft, 0F, 0F, 0F);
      shodright = new ModelRenderer(this, 50, 5);
      shodright.addBox(0F, -1F, 0F, 1, 2, 2);
      shodright.setRotationPoint(-8F, -7F, 1F);
      shodright.setTextureSize(64, 32);
      shodright.mirror = true;
      setRotation(shodright, 0F, 0F, 0F);
      spikeright = new ModelRenderer(this, 50, 1);
      spikeright.addBox(0F, 0F, 0F, 1, 1, 2);
      spikeright.setRotationPoint(-8F, -9F, 2F);
      spikeright.setTextureSize(64, 32);
      spikeright.mirror = true;
      setRotation(spikeright, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    super.render(par1Entity, par2, par3, par4, par5, par6, par7);
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    head.render(par7);
    body.render(par7);
    rightarm.render(par7);
    leftarm.render(par7);
    rightleg.render(par7);
    leftleg.render(par7);
    shoulderright.render(par7);
    shoulderleft.render(par7);
    spikeleft.render(par7);
    shodleft.render(par7);
    shodright.render(par7);
    spikeright.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    
    this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
  }

}
